---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: radarr
  name: radarr
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: radarr
    spec:
      containers:
      - image: hotio/radarr
        name: radarr
        ports:
        - containerPort: 7878
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kube-vip.io/loadbalancerIPs: 192.168.45.55
    metallb.io/ip-allocated-from-pool: pool
  creationTimestamp: "2025-03-29T03:08:43Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    run: radarr
  name: radarr
  namespace: media
  resourceVersion: "1627907"
  uid: 7b577785-fd0a-4521-9df0-218d2719daa7
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.110.198.192
  clusterIPs:
  - 10.110.198.192
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  loadBalancerIP: 192.168.45.55
  ports:
  - nodePort: 31994
    port: 7878
    protocol: TCP
    targetPort: 7878
  selector:
    run: radarr
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.168.45.55
      ipMode: VIP