---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  labels:
    app: radarr
  namespace: media
spec:
  selector:
    app: radarr
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 7878
      targetPort: 7878