---
apiVersion: v1
kind: Service
metadata:
  name: wizarr
  labels:
    app: wizarr
  namespace: media
spec:
  selector:
    app: wizarr
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 5690
      targetPort: 5690