---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nextcloud
  name: nextcloud
  namespace: cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
      - image: library/nextcloud
        name: nextcloud
        ports:
        - containerPort: 80
        env:
        - name: NEXTCLOUD_ADMIN_USER
          value: admin
        - name: NEXTCLOUD_ADMIN_PASSWORD
          value: changeme
        - name: NEXTCLOUD_TRUSTED_DOMAINS
          value: cloud.${DOMAIN} nextcloud
        - name: PHP_UPLOAD_LIMIT
          value: 50G
        - name: PHP_MEMORY_LIMIT
          value: 50G