---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: overseerr-appdata
  namespace: media
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi