---
apiVersion: v1
kind: Service
metadata:
  name: plex
  labels:
    app: plex
  namespace: media
spec:
  selector:
    app: plex
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 32400
      targetPort: 32400