---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: watch.cafio.co
  namespace: media
spec:
  secretName: watch.cafio.co-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
  - "watch.cafio.co"
  - "invite.watch.cafio.co"
  - "request.watch.cafio.co"
  - "movies.watch.cafio.co"
  - "shows.watch.cafio.co"
  - "dl.watch.cafio.co"