---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gitea
  name: gitea
  namespace: cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
      - image: gitea/gitea
        name: gitea
        ports:
        - containerPort: 3000
        env:
        - name: domain
          value: git.cafio.co
        - name: SHOW_USER_EMAIL
          value: "false"
        - name: REVERSE_PROXY_TRUSTED_PROXIES
          value: 127.0.0.0/8,cafio.co
        - name: EMAIL_DOMAIN_ALLOWLIST
          value: cafio.co
        volumeMounts:
        - name: gitea-appdata
          mountPath: /config
      volumes:
        - name: gitea-appdata
          persistentVolumeClaim:
            claimName: gitea-appdata