---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pastefy-prod
  labels:
    app: pastefy-prod
spec:
  selector:
    matchLabels:
      app: pastefy-prod
  template:
    metadata:
      labels:
        app: pastefy-prod
    spec:
      containers:
        - name: pastefy-prod
          image: '${CI_REGISTRY}/${CI_PROJECT_PATH}:${BRANCH_SLUG_SHORT}-${CI_COMMIT_SHORT_SHA}'
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: pastefy-env
      imagePullSecrets:
        - name: 'docker-registry'
  revisionHistoryLimit: 1