---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  labels:
    app: sonarr
  namespace: media
spec:
  selector:
    app: sonarr
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8989
      targetPort: 8989