---
apiVersion: v1
kind: Service
metadata:
  name: sabnzbd
  labels:
    app: sabnzbd
  namespace: media
spec:
  selector:
    app: sabnzbd
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080