---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gist
  labels:
    app: gist
  namespace: cloud
  annotations:
    # cert-manager.io/cluster-issuer: "letsencrypt-production"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    flame.pawelmalak/type: application
    flame.pawelmalak/name: Gist
    flame.pawelmalak/url: https://gist.git.cafio.co/
    flame.pawelmalak/icon: content-paste
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - gist.git.cafio.co
    secretName: cafio.co-tls
  rules:
  - host: gist.git.cafio.co
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gist
            port:
              number: 6157