---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gist-appdata
  namespace: cloud
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi