---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flame
  name: flame
  namespace: cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flame
  template:
    metadata:
      labels:
        app: flame
    spec:
      containers:
      - image: pawelmalak/flame
        name: flame
        ports:
        - containerPort: 5005
        volumeMounts:
        - name: flame-appdata
          mountPath: /app/data
        env:
        - name: PASSWORD
          valueFrom:
            - secretRef:
                name: flame-secret
                key: PASSWORD
      volumes:
        - name: flame-appdata
          persistentVolumeClaim:
            claimName: flame-appdata