---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: <app-name>-appdata
  namespace: <app-namespace>
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi