---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vaultwarden
  name: vaultwarden
  namespace: cloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      containers:
      - image: vaultwarden/server
        name: vaultwarden
        ports:
        - containerPort: 80
        env:
        - name: DOMAIN
          value: vault.${DOMAIN}
        - name: SENDS_ALLOWED
          value: "true"
        - name: EMERGENCY_ACCESS_ALLOWED
          value: "true"
        - name: ADMIN_TOKEN
          value: ""
        - name: WEB_VAULT_ENABLED
          value: "true"
        - name: SIGNUPS_ALLOWED
          value: "false"
        - name: SIGNUPS_VERIFY
          value: "false"
        volumeMounts:
        - name: vaultwarden-appdata
          mountPath: /config
      volumes:
        - name: vaultwarden-appdata
          persistentVolumeClaim:
            claimName: vaultwarden-appdata